// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: services/v1/organization.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1consortium_backend "v1consortium/api/pbentity"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Organization Management Messages
type CreateOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty" dc:"'internal', 'client', 'provider'"` // "internal", "client", "provider"
	UsdotNumber    string                 `protobuf:"bytes,3,opt,name=usdot_number,json=usdotNumber,proto3" json:"usdot_number,omitempty"`
	McNumber       string                 `protobuf:"bytes,4,opt,name=mc_number,json=mcNumber,proto3" json:"mc_number,omitempty"`
	Industry       string                 `protobuf:"bytes,5,opt,name=industry,proto3" json:"industry,omitempty"`
	IsDotRegulated bool                   `protobuf:"varint,6,opt,name=is_dot_regulated,json=isDotRegulated,proto3" json:"is_dot_regulated,omitempty"`
	AddressLine1   string                 `protobuf:"bytes,7,opt,name=address_line1,json=addressLine1,proto3" json:"address_line1,omitempty"`
	AddressLine2   string                 `protobuf:"bytes,8,opt,name=address_line2,json=addressLine2,proto3" json:"address_line2,omitempty"`
	City           string                 `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	State          string                 `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode        string                 `protobuf:"bytes,11,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country        string                 `protobuf:"bytes,12,opt,name=country,proto3" json:"country,omitempty"`
	Phone          string                 `protobuf:"bytes,13,opt,name=phone,proto3" json:"phone,omitempty"`
	Email          string                 `protobuf:"bytes,14,opt,name=email,proto3" json:"email,omitempty"`
	Website        string                 `protobuf:"bytes,15,opt,name=website,proto3" json:"website,omitempty"`
	TaxId          string                 `protobuf:"bytes,16,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	Settings       string                 `protobuf:"bytes,17,opt,name=settings,proto3" json:"settings,omitempty" dc:"JSON string"` // JSON string
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateOrganizationRequest) GetUsdotNumber() string {
	if x != nil {
		return x.UsdotNumber
	}
	return ""
}

func (x *CreateOrganizationRequest) GetMcNumber() string {
	if x != nil {
		return x.McNumber
	}
	return ""
}

func (x *CreateOrganizationRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CreateOrganizationRequest) GetIsDotRegulated() bool {
	if x != nil {
		return x.IsDotRegulated
	}
	return false
}

func (x *CreateOrganizationRequest) GetAddressLine1() string {
	if x != nil {
		return x.AddressLine1
	}
	return ""
}

func (x *CreateOrganizationRequest) GetAddressLine2() string {
	if x != nil {
		return x.AddressLine2
	}
	return ""
}

func (x *CreateOrganizationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateOrganizationRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateOrganizationRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *CreateOrganizationRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateOrganizationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateOrganizationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateOrganizationRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *CreateOrganizationRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *CreateOrganizationRequest) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

type CreateOrganizationResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Organization  *v1consortium_backend.Organizations `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrganizationResponse) GetOrganization() *v1consortium_backend.Organizations {
	if x != nil {
		return x.Organization
	}
	return nil
}

type GetOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetOrganizationRequest) Reset() {
	*x = GetOrganizationRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationRequest) ProtoMessage() {}

func (x *GetOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationRequest.ProtoReflect.Descriptor instead.
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetOrganizationResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Organization  *v1consortium_backend.Organizations `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationResponse) Reset() {
	*x = GetOrganizationResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResponse) ProtoMessage() {}

func (x *GetOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationResponse.ProtoReflect.Descriptor instead.
func (*GetOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrganizationResponse) GetOrganization() *v1consortium_backend.Organizations {
	if x != nil {
		return x.Organization
	}
	return nil
}

type UpdateOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UsdotNumber    string                 `protobuf:"bytes,3,opt,name=usdot_number,json=usdotNumber,proto3" json:"usdot_number,omitempty"`
	McNumber       string                 `protobuf:"bytes,4,opt,name=mc_number,json=mcNumber,proto3" json:"mc_number,omitempty"`
	Industry       string                 `protobuf:"bytes,5,opt,name=industry,proto3" json:"industry,omitempty"`
	IsDotRegulated bool                   `protobuf:"varint,6,opt,name=is_dot_regulated,json=isDotRegulated,proto3" json:"is_dot_regulated,omitempty"`
	AddressLine1   string                 `protobuf:"bytes,7,opt,name=address_line1,json=addressLine1,proto3" json:"address_line1,omitempty"`
	AddressLine2   string                 `protobuf:"bytes,8,opt,name=address_line2,json=addressLine2,proto3" json:"address_line2,omitempty"`
	City           string                 `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	State          string                 `protobuf:"bytes,10,opt,name=state,proto3" json:"state,omitempty"`
	ZipCode        string                 `protobuf:"bytes,11,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Country        string                 `protobuf:"bytes,12,opt,name=country,proto3" json:"country,omitempty"`
	Phone          string                 `protobuf:"bytes,13,opt,name=phone,proto3" json:"phone,omitempty"`
	Email          string                 `protobuf:"bytes,14,opt,name=email,proto3" json:"email,omitempty"`
	Website        string                 `protobuf:"bytes,15,opt,name=website,proto3" json:"website,omitempty"`
	Settings       string                 `protobuf:"bytes,16,opt,name=settings,proto3" json:"settings,omitempty" dc:"JSON string"` // JSON string
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrganizationRequest) Reset() {
	*x = UpdateOrganizationRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationRequest) ProtoMessage() {}

func (x *UpdateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetUsdotNumber() string {
	if x != nil {
		return x.UsdotNumber
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetMcNumber() string {
	if x != nil {
		return x.McNumber
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetIsDotRegulated() bool {
	if x != nil {
		return x.IsDotRegulated
	}
	return false
}

func (x *UpdateOrganizationRequest) GetAddressLine1() string {
	if x != nil {
		return x.AddressLine1
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetAddressLine2() string {
	if x != nil {
		return x.AddressLine2
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *UpdateOrganizationRequest) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

type UpdateOrganizationResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Organization  *v1consortium_backend.Organizations `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationResponse) Reset() {
	*x = UpdateOrganizationResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationResponse) ProtoMessage() {}

func (x *UpdateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOrganizationResponse) GetOrganization() *v1consortium_backend.Organizations {
	if x != nil {
		return x.Organization
	}
	return nil
}

type ListOrganizationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty" dc:"Filter by organization type"` // Filter by organization type
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Search        string                 `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty" dc:"Search by name, email, etc."` // Search by name, email, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsRequest) Reset() {
	*x = ListOrganizationsRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsRequest) ProtoMessage() {}

func (x *ListOrganizationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsRequest.ProtoReflect.Descriptor instead.
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrganizationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrganizationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrganizationsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListOrganizationsRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ListOrganizationsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListOrganizationsResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Organizations []*v1consortium_backend.Organizations `protobuf:"bytes,1,rep,name=organizations,proto3" json:"organizations,omitempty"`
	TotalCount    int32                                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                                 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrganizationsResponse) Reset() {
	*x = ListOrganizationsResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrganizationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrganizationsResponse) ProtoMessage() {}

func (x *ListOrganizationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrganizationsResponse.ProtoReflect.Descriptor instead.
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrganizationsResponse) GetOrganizations() []*v1consortium_backend.Organizations {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *ListOrganizationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListOrganizationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrganizationsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeactivateOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeactivateOrganizationRequest) Reset() {
	*x = DeactivateOrganizationRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateOrganizationRequest) ProtoMessage() {}

func (x *DeactivateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeactivateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivateOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *DeactivateOrganizationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeactivateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateOrganizationResponse) Reset() {
	*x = DeactivateOrganizationResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateOrganizationResponse) ProtoMessage() {}

func (x *DeactivateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*DeactivateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{9}
}

func (x *DeactivateOrganizationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// User Management Messages
type CreateUserRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId               string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Role                         string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	EmployeeId                   string                 `protobuf:"bytes,3,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	FirstName                    string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                     string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                        string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone                        string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth                  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	SsnLastFour                  string                 `protobuf:"bytes,9,opt,name=ssn_last_four,json=ssnLastFour,proto3" json:"ssn_last_four,omitempty"`
	HireDate                     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=hire_date,json=hireDate,proto3" json:"hire_date,omitempty"`
	RequiresDotTesting           bool                   `protobuf:"varint,11,opt,name=requires_dot_testing,json=requiresDotTesting,proto3" json:"requires_dot_testing,omitempty"`
	RequiresNonDotTesting        bool                   `protobuf:"varint,12,opt,name=requires_non_dot_testing,json=requiresNonDotTesting,proto3" json:"requires_non_dot_testing,omitempty"`
	CdlNumber                    string                 `protobuf:"bytes,13,opt,name=cdl_number,json=cdlNumber,proto3" json:"cdl_number,omitempty"`
	CdlState                     string                 `protobuf:"bytes,14,opt,name=cdl_state,json=cdlState,proto3" json:"cdl_state,omitempty"`
	CdlExpirationDate            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=cdl_expiration_date,json=cdlExpirationDate,proto3" json:"cdl_expiration_date,omitempty"`
	JobTitle                     string                 `protobuf:"bytes,16,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Department                   string                 `protobuf:"bytes,17,opt,name=department,proto3" json:"department,omitempty"`
	SupervisorId                 string                 `protobuf:"bytes,18,opt,name=supervisor_id,json=supervisorId,proto3" json:"supervisor_id,omitempty"`
	EmergencyContactName         string                 `protobuf:"bytes,19,opt,name=emergency_contact_name,json=emergencyContactName,proto3" json:"emergency_contact_name,omitempty"`
	EmergencyContactPhone        string                 `protobuf:"bytes,20,opt,name=emergency_contact_phone,json=emergencyContactPhone,proto3" json:"emergency_contact_phone,omitempty"`
	EmergencyContactRelationship string                 `protobuf:"bytes,21,opt,name=emergency_contact_relationship,json=emergencyContactRelationship,proto3" json:"emergency_contact_relationship,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{10}
}

func (x *CreateUserRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateUserRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *CreateUserRequest) GetSsnLastFour() string {
	if x != nil {
		return x.SsnLastFour
	}
	return ""
}

func (x *CreateUserRequest) GetHireDate() *timestamppb.Timestamp {
	if x != nil {
		return x.HireDate
	}
	return nil
}

func (x *CreateUserRequest) GetRequiresDotTesting() bool {
	if x != nil {
		return x.RequiresDotTesting
	}
	return false
}

func (x *CreateUserRequest) GetRequiresNonDotTesting() bool {
	if x != nil {
		return x.RequiresNonDotTesting
	}
	return false
}

func (x *CreateUserRequest) GetCdlNumber() string {
	if x != nil {
		return x.CdlNumber
	}
	return ""
}

func (x *CreateUserRequest) GetCdlState() string {
	if x != nil {
		return x.CdlState
	}
	return ""
}

func (x *CreateUserRequest) GetCdlExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CdlExpirationDate
	}
	return nil
}

func (x *CreateUserRequest) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *CreateUserRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateUserRequest) GetSupervisorId() string {
	if x != nil {
		return x.SupervisorId
	}
	return ""
}

func (x *CreateUserRequest) GetEmergencyContactName() string {
	if x != nil {
		return x.EmergencyContactName
	}
	return ""
}

func (x *CreateUserRequest) GetEmergencyContactPhone() string {
	if x != nil {
		return x.EmergencyContactPhone
	}
	return ""
}

func (x *CreateUserRequest) GetEmergencyContactRelationship() string {
	if x != nil {
		return x.EmergencyContactRelationship
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	User          *v1consortium_backend.UserProfiles `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUserResponse) GetUser() *v1consortium_backend.UserProfiles {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	User          *v1consortium_backend.UserProfiles `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserResponse) GetUser() *v1consortium_backend.UserProfiles {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	UserId                       string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role                         string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	EmployeeId                   string                 `protobuf:"bytes,3,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	FirstName                    string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName                     string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                        string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone                        string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	DateOfBirth                  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	SsnLastFour                  string                 `protobuf:"bytes,9,opt,name=ssn_last_four,json=ssnLastFour,proto3" json:"ssn_last_four,omitempty"`
	HireDate                     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=hire_date,json=hireDate,proto3" json:"hire_date,omitempty"`
	TerminationDate              *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=termination_date,json=terminationDate,proto3" json:"termination_date,omitempty"`
	IsActive                     bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	RequiresDotTesting           bool                   `protobuf:"varint,13,opt,name=requires_dot_testing,json=requiresDotTesting,proto3" json:"requires_dot_testing,omitempty"`
	RequiresNonDotTesting        bool                   `protobuf:"varint,14,opt,name=requires_non_dot_testing,json=requiresNonDotTesting,proto3" json:"requires_non_dot_testing,omitempty"`
	CdlNumber                    string                 `protobuf:"bytes,15,opt,name=cdl_number,json=cdlNumber,proto3" json:"cdl_number,omitempty"`
	CdlState                     string                 `protobuf:"bytes,16,opt,name=cdl_state,json=cdlState,proto3" json:"cdl_state,omitempty"`
	CdlExpirationDate            *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=cdl_expiration_date,json=cdlExpirationDate,proto3" json:"cdl_expiration_date,omitempty"`
	JobTitle                     string                 `protobuf:"bytes,18,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	Department                   string                 `protobuf:"bytes,19,opt,name=department,proto3" json:"department,omitempty"`
	SupervisorId                 string                 `protobuf:"bytes,20,opt,name=supervisor_id,json=supervisorId,proto3" json:"supervisor_id,omitempty"`
	EmergencyContactName         string                 `protobuf:"bytes,21,opt,name=emergency_contact_name,json=emergencyContactName,proto3" json:"emergency_contact_name,omitempty"`
	EmergencyContactPhone        string                 `protobuf:"bytes,22,opt,name=emergency_contact_phone,json=emergencyContactPhone,proto3" json:"emergency_contact_phone,omitempty"`
	EmergencyContactRelationship string                 `protobuf:"bytes,23,opt,name=emergency_contact_relationship,json=emergencyContactRelationship,proto3" json:"emergency_contact_relationship,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateUserRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UpdateUserRequest) GetSsnLastFour() string {
	if x != nil {
		return x.SsnLastFour
	}
	return ""
}

func (x *UpdateUserRequest) GetHireDate() *timestamppb.Timestamp {
	if x != nil {
		return x.HireDate
	}
	return nil
}

func (x *UpdateUserRequest) GetTerminationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TerminationDate
	}
	return nil
}

func (x *UpdateUserRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateUserRequest) GetRequiresDotTesting() bool {
	if x != nil {
		return x.RequiresDotTesting
	}
	return false
}

func (x *UpdateUserRequest) GetRequiresNonDotTesting() bool {
	if x != nil {
		return x.RequiresNonDotTesting
	}
	return false
}

func (x *UpdateUserRequest) GetCdlNumber() string {
	if x != nil {
		return x.CdlNumber
	}
	return ""
}

func (x *UpdateUserRequest) GetCdlState() string {
	if x != nil {
		return x.CdlState
	}
	return ""
}

func (x *UpdateUserRequest) GetCdlExpirationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CdlExpirationDate
	}
	return nil
}

func (x *UpdateUserRequest) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *UpdateUserRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *UpdateUserRequest) GetSupervisorId() string {
	if x != nil {
		return x.SupervisorId
	}
	return ""
}

func (x *UpdateUserRequest) GetEmergencyContactName() string {
	if x != nil {
		return x.EmergencyContactName
	}
	return ""
}

func (x *UpdateUserRequest) GetEmergencyContactPhone() string {
	if x != nil {
		return x.EmergencyContactPhone
	}
	return ""
}

func (x *UpdateUserRequest) GetEmergencyContactRelationship() string {
	if x != nil {
		return x.EmergencyContactRelationship
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	User          *v1consortium_backend.UserProfiles `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateUserResponse) GetUser() *v1consortium_backend.UserProfiles {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUsersRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId     string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Page               int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize           int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Role               string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty" dc:"Filter by role"` // Filter by role
	IsActive           bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Search             string                 `protobuf:"bytes,6,opt,name=search,proto3" json:"search,omitempty" dc:"Search by name, email, employee_id"` // Search by name, email, employee_id
	RequiresDotTesting bool                   `protobuf:"varint,7,opt,name=requires_dot_testing,json=requiresDotTesting,proto3" json:"requires_dot_testing,omitempty"`
	Department         string                 `protobuf:"bytes,8,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{16}
}

func (x *ListUsersRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListUsersRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ListUsersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListUsersRequest) GetRequiresDotTesting() bool {
	if x != nil {
		return x.RequiresDotTesting
	}
	return false
}

func (x *ListUsersRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Users         []*v1consortium_backend.UserProfiles `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                                `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                                `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                                `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{17}
}

func (x *ListUsersResponse) GetUsers() []*v1consortium_backend.UserProfiles {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListUsersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeactivateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TerminationDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=termination_date,json=terminationDate,proto3" json:"termination_date,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeactivateUserRequest) Reset() {
	*x = DeactivateUserRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateUserRequest) ProtoMessage() {}

func (x *DeactivateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateUserRequest.ProtoReflect.Descriptor instead.
func (*DeactivateUserRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{18}
}

func (x *DeactivateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeactivateUserRequest) GetTerminationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TerminationDate
	}
	return nil
}

func (x *DeactivateUserRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeactivateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateUserResponse) Reset() {
	*x = DeactivateUserResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateUserResponse) ProtoMessage() {}

func (x *DeactivateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateUserResponse.ProtoReflect.Descriptor instead.
func (*DeactivateUserResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{19}
}

func (x *DeactivateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Subscription Management Messages
type CreateSubscriptionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId       string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PlanId               string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	StartDate            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	StripeSubscriptionId string                 `protobuf:"bytes,5,opt,name=stripe_subscription_id,json=stripeSubscriptionId,proto3" json:"stripe_subscription_id,omitempty"`
	StripeCustomerId     string                 `protobuf:"bytes,6,opt,name=stripe_customer_id,json=stripeCustomerId,proto3" json:"stripe_customer_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateSubscriptionRequest) Reset() {
	*x = CreateSubscriptionRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionRequest) ProtoMessage() {}

func (x *CreateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{20}
}

func (x *CreateSubscriptionRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *CreateSubscriptionRequest) GetStripeSubscriptionId() string {
	if x != nil {
		return x.StripeSubscriptionId
	}
	return ""
}

func (x *CreateSubscriptionRequest) GetStripeCustomerId() string {
	if x != nil {
		return x.StripeCustomerId
	}
	return ""
}

type CreateSubscriptionResponse struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	Subscription  *v1consortium_backend.OrganizationSubscriptions `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubscriptionResponse) Reset() {
	*x = CreateSubscriptionResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubscriptionResponse) ProtoMessage() {}

func (x *CreateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{21}
}

func (x *CreateSubscriptionResponse) GetSubscription() *v1consortium_backend.OrganizationSubscriptions {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type GetSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{22}
}

func (x *GetSubscriptionRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetSubscriptionResponse struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	Subscription  *v1consortium_backend.OrganizationSubscriptions `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Plan          *v1consortium_backend.SubscriptionPlans         `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{23}
}

func (x *GetSubscriptionResponse) GetSubscription() *v1consortium_backend.OrganizationSubscriptions {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *GetSubscriptionResponse) GetPlan() *v1consortium_backend.SubscriptionPlans {
	if x != nil {
		return x.Plan
	}
	return nil
}

type UpdateSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	PlanId         string                 `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	EndDate        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSubscriptionRequest) Reset() {
	*x = UpdateSubscriptionRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionRequest) ProtoMessage() {}

func (x *UpdateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *UpdateSubscriptionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateSubscriptionResponse struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	Subscription  *v1consortium_backend.OrganizationSubscriptions `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionResponse) Reset() {
	*x = UpdateSubscriptionResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionResponse) ProtoMessage() {}

func (x *UpdateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateSubscriptionResponse) GetSubscription() *v1consortium_backend.OrganizationSubscriptions {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type ListSubscriptionPlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsActive      bool                   `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionPlansRequest) Reset() {
	*x = ListSubscriptionPlansRequest{}
	mi := &file_services_v1_organization_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionPlansRequest) ProtoMessage() {}

func (x *ListSubscriptionPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionPlansRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionPlansRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{26}
}

func (x *ListSubscriptionPlansRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListSubscriptionPlansResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Plans         []*v1consortium_backend.SubscriptionPlans `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionPlansResponse) Reset() {
	*x = ListSubscriptionPlansResponse{}
	mi := &file_services_v1_organization_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionPlansResponse) ProtoMessage() {}

func (x *ListSubscriptionPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_organization_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionPlansResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionPlansResponse) Descriptor() ([]byte, []int) {
	return file_services_v1_organization_proto_rawDescGZIP(), []int{27}
}

func (x *ListSubscriptionPlansResponse) GetPlans() []*v1consortium_backend.SubscriptionPlans {
	if x != nil {
		return x.Plans
	}
	return nil
}

var File_services_v1_organization_proto protoreflect.FileDescriptor

const file_services_v1_organization_proto_rawDesc = "" +
	"\n" +
	"\x1eservices/v1/organization.proto\x12\x15v1consortium.services\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cpbentity/organizations.proto\x1a\x1cpbentity/user_profiles.proto\x1a)pbentity/organization_subscriptions.proto\x1a!pbentity/subscription_plans.proto\"\xeb\x03\n" +
	"\x19CreateOrganizationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fusdot_number\x18\x03 \x01(\tR\vusdotNumber\x12\x1b\n" +
	"\tmc_number\x18\x04 \x01(\tR\bmcNumber\x12\x1a\n" +
	"\bindustry\x18\x05 \x01(\tR\bindustry\x12(\n" +
	"\x10is_dot_regulated\x18\x06 \x01(\bR\x0eisDotRegulated\x12#\n" +
	"\raddress_line1\x18\a \x01(\tR\faddressLine1\x12#\n" +
	"\raddress_line2\x18\b \x01(\tR\faddressLine2\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\v \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\f \x01(\tR\acountry\x12\x14\n" +
	"\x05phone\x18\r \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x0e \x01(\tR\x05email\x12\x18\n" +
	"\awebsite\x18\x0f \x01(\tR\awebsite\x12\x15\n" +
	"\x06tax_id\x18\x10 \x01(\tR\x05taxId\x12\x1a\n" +
	"\bsettings\x18\x11 \x01(\tR\bsettings\"e\n" +
	"\x1aCreateOrganizationResponse\x12G\n" +
	"\forganization\x18\x01 \x01(\v2#.v1consortium.backend.OrganizationsR\forganization\"A\n" +
	"\x16GetOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"b\n" +
	"\x17GetOrganizationResponse\x12G\n" +
	"\forganization\x18\x01 \x01(\v2#.v1consortium.backend.OrganizationsR\forganization\"\xe9\x03\n" +
	"\x19UpdateOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fusdot_number\x18\x03 \x01(\tR\vusdotNumber\x12\x1b\n" +
	"\tmc_number\x18\x04 \x01(\tR\bmcNumber\x12\x1a\n" +
	"\bindustry\x18\x05 \x01(\tR\bindustry\x12(\n" +
	"\x10is_dot_regulated\x18\x06 \x01(\bR\x0eisDotRegulated\x12#\n" +
	"\raddress_line1\x18\a \x01(\tR\faddressLine1\x12#\n" +
	"\raddress_line2\x18\b \x01(\tR\faddressLine2\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\n" +
	" \x01(\tR\x05state\x12\x19\n" +
	"\bzip_code\x18\v \x01(\tR\azipCode\x12\x18\n" +
	"\acountry\x18\f \x01(\tR\acountry\x12\x14\n" +
	"\x05phone\x18\r \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x0e \x01(\tR\x05email\x12\x18\n" +
	"\awebsite\x18\x0f \x01(\tR\awebsite\x12\x1a\n" +
	"\bsettings\x18\x10 \x01(\tR\bsettings\"e\n" +
	"\x1aUpdateOrganizationResponse\x12G\n" +
	"\forganization\x18\x01 \x01(\v2#.v1consortium.backend.OrganizationsR\forganization\"\x94\x01\n" +
	"\x18ListOrganizationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\"\xb8\x01\n" +
	"\x19ListOrganizationsResponse\x12I\n" +
	"\rorganizations\x18\x01 \x03(\v2#.v1consortium.backend.OrganizationsR\rorganizations\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"`\n" +
	"\x1dDeactivateOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\":\n" +
	"\x1eDeactivateOrganizationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xff\x06\n" +
	"\x11CreateUserRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1f\n" +
	"\vemployee_id\x18\x03 \x01(\tR\n" +
	"employeeId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12>\n" +
	"\rdate_of_birth\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\"\n" +
	"\rssn_last_four\x18\t \x01(\tR\vssnLastFour\x127\n" +
	"\thire_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bhireDate\x120\n" +
	"\x14requires_dot_testing\x18\v \x01(\bR\x12requiresDotTesting\x127\n" +
	"\x18requires_non_dot_testing\x18\f \x01(\bR\x15requiresNonDotTesting\x12\x1d\n" +
	"\n" +
	"cdl_number\x18\r \x01(\tR\tcdlNumber\x12\x1b\n" +
	"\tcdl_state\x18\x0e \x01(\tR\bcdlState\x12J\n" +
	"\x13cdl_expiration_date\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x11cdlExpirationDate\x12\x1b\n" +
	"\tjob_title\x18\x10 \x01(\tR\bjobTitle\x12\x1e\n" +
	"\n" +
	"department\x18\x11 \x01(\tR\n" +
	"department\x12#\n" +
	"\rsupervisor_id\x18\x12 \x01(\tR\fsupervisorId\x124\n" +
	"\x16emergency_contact_name\x18\x13 \x01(\tR\x14emergencyContactName\x126\n" +
	"\x17emergency_contact_phone\x18\x14 \x01(\tR\x15emergencyContactPhone\x12D\n" +
	"\x1eemergency_contact_relationship\x18\x15 \x01(\tR\x1cemergencyContactRelationship\"L\n" +
	"\x12CreateUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".v1consortium.backend.UserProfilesR\x04user\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"I\n" +
	"\x0fGetUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".v1consortium.backend.UserProfilesR\x04user\"\xd3\a\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1f\n" +
	"\vemployee_id\x18\x03 \x01(\tR\n" +
	"employeeId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12>\n" +
	"\rdate_of_birth\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\"\n" +
	"\rssn_last_four\x18\t \x01(\tR\vssnLastFour\x127\n" +
	"\thire_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bhireDate\x12E\n" +
	"\x10termination_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0fterminationDate\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x120\n" +
	"\x14requires_dot_testing\x18\r \x01(\bR\x12requiresDotTesting\x127\n" +
	"\x18requires_non_dot_testing\x18\x0e \x01(\bR\x15requiresNonDotTesting\x12\x1d\n" +
	"\n" +
	"cdl_number\x18\x0f \x01(\tR\tcdlNumber\x12\x1b\n" +
	"\tcdl_state\x18\x10 \x01(\tR\bcdlState\x12J\n" +
	"\x13cdl_expiration_date\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x11cdlExpirationDate\x12\x1b\n" +
	"\tjob_title\x18\x12 \x01(\tR\bjobTitle\x12\x1e\n" +
	"\n" +
	"department\x18\x13 \x01(\tR\n" +
	"department\x12#\n" +
	"\rsupervisor_id\x18\x14 \x01(\tR\fsupervisorId\x124\n" +
	"\x16emergency_contact_name\x18\x15 \x01(\tR\x14emergencyContactName\x126\n" +
	"\x17emergency_contact_phone\x18\x16 \x01(\tR\x15emergencyContactPhone\x12D\n" +
	"\x1eemergency_contact_relationship\x18\x17 \x01(\tR\x1cemergencyContactRelationship\"L\n" +
	"\x12UpdateUserResponse\x126\n" +
	"\x04user\x18\x01 \x01(\v2\".v1consortium.backend.UserProfilesR\x04user\"\x87\x02\n" +
	"\x10ListUsersRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x16\n" +
	"\x06search\x18\x06 \x01(\tR\x06search\x120\n" +
	"\x14requires_dot_testing\x18\a \x01(\bR\x12requiresDotTesting\x12\x1e\n" +
	"\n" +
	"department\x18\b \x01(\tR\n" +
	"department\"\x9f\x01\n" +
	"\x11ListUsersResponse\x128\n" +
	"\x05users\x18\x01 \x03(\v2\".v1consortium.backend.UserProfilesR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x8f\x01\n" +
	"\x15DeactivateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12E\n" +
	"\x10termination_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0fterminationDate\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"2\n" +
	"\x16DeactivateUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb3\x02\n" +
	"\x19CreateSubscriptionRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x124\n" +
	"\x16stripe_subscription_id\x18\x05 \x01(\tR\x14stripeSubscriptionId\x12,\n" +
	"\x12stripe_customer_id\x18\x06 \x01(\tR\x10stripeCustomerId\"q\n" +
	"\x1aCreateSubscriptionResponse\x12S\n" +
	"\fsubscription\x18\x01 \x01(\v2/.v1consortium.backend.OrganizationSubscriptionsR\fsubscription\"A\n" +
	"\x16GetSubscriptionRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"\xab\x01\n" +
	"\x17GetSubscriptionResponse\x12S\n" +
	"\fsubscription\x18\x01 \x01(\v2/.v1consortium.backend.OrganizationSubscriptionsR\fsubscription\x12;\n" +
	"\x04plan\x18\x02 \x01(\v2'.v1consortium.backend.SubscriptionPlansR\x04plan\"\xac\x01\n" +
	"\x19UpdateSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"q\n" +
	"\x1aUpdateSubscriptionResponse\x12S\n" +
	"\fsubscription\x18\x01 \x01(\v2/.v1consortium.backend.OrganizationSubscriptionsR\fsubscription\";\n" +
	"\x1cListSubscriptionPlansRequest\x12\x1b\n" +
	"\tis_active\x18\x01 \x01(\bR\bisActive\"^\n" +
	"\x1dListSubscriptionPlansResponse\x12=\n" +
	"\x05plans\x18\x01 \x03(\v2'.v1consortium.backend.SubscriptionPlansR\x05plans2\xd9\f\n" +
	"\x13OrganizationService\x12y\n" +
	"\x12CreateOrganization\x120.v1consortium.services.CreateOrganizationRequest\x1a1.v1consortium.services.CreateOrganizationResponse\x12p\n" +
	"\x0fGetOrganization\x12-.v1consortium.services.GetOrganizationRequest\x1a..v1consortium.services.GetOrganizationResponse\x12y\n" +
	"\x12UpdateOrganization\x120.v1consortium.services.UpdateOrganizationRequest\x1a1.v1consortium.services.UpdateOrganizationResponse\x12v\n" +
	"\x11ListOrganizations\x12/.v1consortium.services.ListOrganizationsRequest\x1a0.v1consortium.services.ListOrganizationsResponse\x12\x85\x01\n" +
	"\x16DeactivateOrganization\x124.v1consortium.services.DeactivateOrganizationRequest\x1a5.v1consortium.services.DeactivateOrganizationResponse\x12a\n" +
	"\n" +
	"CreateUser\x12(.v1consortium.services.CreateUserRequest\x1a).v1consortium.services.CreateUserResponse\x12X\n" +
	"\aGetUser\x12%.v1consortium.services.GetUserRequest\x1a&.v1consortium.services.GetUserResponse\x12a\n" +
	"\n" +
	"UpdateUser\x12(.v1consortium.services.UpdateUserRequest\x1a).v1consortium.services.UpdateUserResponse\x12^\n" +
	"\tListUsers\x12'.v1consortium.services.ListUsersRequest\x1a(.v1consortium.services.ListUsersResponse\x12m\n" +
	"\x0eDeactivateUser\x12,.v1consortium.services.DeactivateUserRequest\x1a-.v1consortium.services.DeactivateUserResponse\x12y\n" +
	"\x12CreateSubscription\x120.v1consortium.services.CreateSubscriptionRequest\x1a1.v1consortium.services.CreateSubscriptionResponse\x12p\n" +
	"\x0fGetSubscription\x12-.v1consortium.services.GetSubscriptionRequest\x1a..v1consortium.services.GetSubscriptionResponse\x12y\n" +
	"\x12UpdateSubscription\x120.v1consortium.services.UpdateSubscriptionRequest\x1a1.v1consortium.services.UpdateSubscriptionResponse\x12\x82\x01\n" +
	"\x15ListSubscriptionPlans\x123.v1consortium.services.ListSubscriptionPlansRequest\x1a4.v1consortium.services.ListSubscriptionPlansResponseB\rZ\vservices/v1b\x06proto3"

var (
	file_services_v1_organization_proto_rawDescOnce sync.Once
	file_services_v1_organization_proto_rawDescData []byte
)

func file_services_v1_organization_proto_rawDescGZIP() []byte {
	file_services_v1_organization_proto_rawDescOnce.Do(func() {
		file_services_v1_organization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_v1_organization_proto_rawDesc), len(file_services_v1_organization_proto_rawDesc)))
	})
	return file_services_v1_organization_proto_rawDescData
}

var file_services_v1_organization_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_services_v1_organization_proto_goTypes = []any{
	(*CreateOrganizationRequest)(nil),                      // 0: v1consortium.services.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil),                     // 1: v1consortium.services.CreateOrganizationResponse
	(*GetOrganizationRequest)(nil),                         // 2: v1consortium.services.GetOrganizationRequest
	(*GetOrganizationResponse)(nil),                        // 3: v1consortium.services.GetOrganizationResponse
	(*UpdateOrganizationRequest)(nil),                      // 4: v1consortium.services.UpdateOrganizationRequest
	(*UpdateOrganizationResponse)(nil),                     // 5: v1consortium.services.UpdateOrganizationResponse
	(*ListOrganizationsRequest)(nil),                       // 6: v1consortium.services.ListOrganizationsRequest
	(*ListOrganizationsResponse)(nil),                      // 7: v1consortium.services.ListOrganizationsResponse
	(*DeactivateOrganizationRequest)(nil),                  // 8: v1consortium.services.DeactivateOrganizationRequest
	(*DeactivateOrganizationResponse)(nil),                 // 9: v1consortium.services.DeactivateOrganizationResponse
	(*CreateUserRequest)(nil),                              // 10: v1consortium.services.CreateUserRequest
	(*CreateUserResponse)(nil),                             // 11: v1consortium.services.CreateUserResponse
	(*GetUserRequest)(nil),                                 // 12: v1consortium.services.GetUserRequest
	(*GetUserResponse)(nil),                                // 13: v1consortium.services.GetUserResponse
	(*UpdateUserRequest)(nil),                              // 14: v1consortium.services.UpdateUserRequest
	(*UpdateUserResponse)(nil),                             // 15: v1consortium.services.UpdateUserResponse
	(*ListUsersRequest)(nil),                               // 16: v1consortium.services.ListUsersRequest
	(*ListUsersResponse)(nil),                              // 17: v1consortium.services.ListUsersResponse
	(*DeactivateUserRequest)(nil),                          // 18: v1consortium.services.DeactivateUserRequest
	(*DeactivateUserResponse)(nil),                         // 19: v1consortium.services.DeactivateUserResponse
	(*CreateSubscriptionRequest)(nil),                      // 20: v1consortium.services.CreateSubscriptionRequest
	(*CreateSubscriptionResponse)(nil),                     // 21: v1consortium.services.CreateSubscriptionResponse
	(*GetSubscriptionRequest)(nil),                         // 22: v1consortium.services.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),                        // 23: v1consortium.services.GetSubscriptionResponse
	(*UpdateSubscriptionRequest)(nil),                      // 24: v1consortium.services.UpdateSubscriptionRequest
	(*UpdateSubscriptionResponse)(nil),                     // 25: v1consortium.services.UpdateSubscriptionResponse
	(*ListSubscriptionPlansRequest)(nil),                   // 26: v1consortium.services.ListSubscriptionPlansRequest
	(*ListSubscriptionPlansResponse)(nil),                  // 27: v1consortium.services.ListSubscriptionPlansResponse
	(*v1consortium_backend.Organizations)(nil),             // 28: v1consortium.backend.Organizations
	(*timestamppb.Timestamp)(nil),                          // 29: google.protobuf.Timestamp
	(*v1consortium_backend.UserProfiles)(nil),              // 30: v1consortium.backend.UserProfiles
	(*v1consortium_backend.OrganizationSubscriptions)(nil), // 31: v1consortium.backend.OrganizationSubscriptions
	(*v1consortium_backend.SubscriptionPlans)(nil),         // 32: v1consortium.backend.SubscriptionPlans
}
var file_services_v1_organization_proto_depIdxs = []int32{
	28, // 0: v1consortium.services.CreateOrganizationResponse.organization:type_name -> v1consortium.backend.Organizations
	28, // 1: v1consortium.services.GetOrganizationResponse.organization:type_name -> v1consortium.backend.Organizations
	28, // 2: v1consortium.services.UpdateOrganizationResponse.organization:type_name -> v1consortium.backend.Organizations
	28, // 3: v1consortium.services.ListOrganizationsResponse.organizations:type_name -> v1consortium.backend.Organizations
	29, // 4: v1consortium.services.CreateUserRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	29, // 5: v1consortium.services.CreateUserRequest.hire_date:type_name -> google.protobuf.Timestamp
	29, // 6: v1consortium.services.CreateUserRequest.cdl_expiration_date:type_name -> google.protobuf.Timestamp
	30, // 7: v1consortium.services.CreateUserResponse.user:type_name -> v1consortium.backend.UserProfiles
	30, // 8: v1consortium.services.GetUserResponse.user:type_name -> v1consortium.backend.UserProfiles
	29, // 9: v1consortium.services.UpdateUserRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	29, // 10: v1consortium.services.UpdateUserRequest.hire_date:type_name -> google.protobuf.Timestamp
	29, // 11: v1consortium.services.UpdateUserRequest.termination_date:type_name -> google.protobuf.Timestamp
	29, // 12: v1consortium.services.UpdateUserRequest.cdl_expiration_date:type_name -> google.protobuf.Timestamp
	30, // 13: v1consortium.services.UpdateUserResponse.user:type_name -> v1consortium.backend.UserProfiles
	30, // 14: v1consortium.services.ListUsersResponse.users:type_name -> v1consortium.backend.UserProfiles
	29, // 15: v1consortium.services.DeactivateUserRequest.termination_date:type_name -> google.protobuf.Timestamp
	29, // 16: v1consortium.services.CreateSubscriptionRequest.start_date:type_name -> google.protobuf.Timestamp
	29, // 17: v1consortium.services.CreateSubscriptionRequest.end_date:type_name -> google.protobuf.Timestamp
	31, // 18: v1consortium.services.CreateSubscriptionResponse.subscription:type_name -> v1consortium.backend.OrganizationSubscriptions
	31, // 19: v1consortium.services.GetSubscriptionResponse.subscription:type_name -> v1consortium.backend.OrganizationSubscriptions
	32, // 20: v1consortium.services.GetSubscriptionResponse.plan:type_name -> v1consortium.backend.SubscriptionPlans
	29, // 21: v1consortium.services.UpdateSubscriptionRequest.end_date:type_name -> google.protobuf.Timestamp
	31, // 22: v1consortium.services.UpdateSubscriptionResponse.subscription:type_name -> v1consortium.backend.OrganizationSubscriptions
	32, // 23: v1consortium.services.ListSubscriptionPlansResponse.plans:type_name -> v1consortium.backend.SubscriptionPlans
	0,  // 24: v1consortium.services.OrganizationService.CreateOrganization:input_type -> v1consortium.services.CreateOrganizationRequest
	2,  // 25: v1consortium.services.OrganizationService.GetOrganization:input_type -> v1consortium.services.GetOrganizationRequest
	4,  // 26: v1consortium.services.OrganizationService.UpdateOrganization:input_type -> v1consortium.services.UpdateOrganizationRequest
	6,  // 27: v1consortium.services.OrganizationService.ListOrganizations:input_type -> v1consortium.services.ListOrganizationsRequest
	8,  // 28: v1consortium.services.OrganizationService.DeactivateOrganization:input_type -> v1consortium.services.DeactivateOrganizationRequest
	10, // 29: v1consortium.services.OrganizationService.CreateUser:input_type -> v1consortium.services.CreateUserRequest
	12, // 30: v1consortium.services.OrganizationService.GetUser:input_type -> v1consortium.services.GetUserRequest
	14, // 31: v1consortium.services.OrganizationService.UpdateUser:input_type -> v1consortium.services.UpdateUserRequest
	16, // 32: v1consortium.services.OrganizationService.ListUsers:input_type -> v1consortium.services.ListUsersRequest
	18, // 33: v1consortium.services.OrganizationService.DeactivateUser:input_type -> v1consortium.services.DeactivateUserRequest
	20, // 34: v1consortium.services.OrganizationService.CreateSubscription:input_type -> v1consortium.services.CreateSubscriptionRequest
	22, // 35: v1consortium.services.OrganizationService.GetSubscription:input_type -> v1consortium.services.GetSubscriptionRequest
	24, // 36: v1consortium.services.OrganizationService.UpdateSubscription:input_type -> v1consortium.services.UpdateSubscriptionRequest
	26, // 37: v1consortium.services.OrganizationService.ListSubscriptionPlans:input_type -> v1consortium.services.ListSubscriptionPlansRequest
	1,  // 38: v1consortium.services.OrganizationService.CreateOrganization:output_type -> v1consortium.services.CreateOrganizationResponse
	3,  // 39: v1consortium.services.OrganizationService.GetOrganization:output_type -> v1consortium.services.GetOrganizationResponse
	5,  // 40: v1consortium.services.OrganizationService.UpdateOrganization:output_type -> v1consortium.services.UpdateOrganizationResponse
	7,  // 41: v1consortium.services.OrganizationService.ListOrganizations:output_type -> v1consortium.services.ListOrganizationsResponse
	9,  // 42: v1consortium.services.OrganizationService.DeactivateOrganization:output_type -> v1consortium.services.DeactivateOrganizationResponse
	11, // 43: v1consortium.services.OrganizationService.CreateUser:output_type -> v1consortium.services.CreateUserResponse
	13, // 44: v1consortium.services.OrganizationService.GetUser:output_type -> v1consortium.services.GetUserResponse
	15, // 45: v1consortium.services.OrganizationService.UpdateUser:output_type -> v1consortium.services.UpdateUserResponse
	17, // 46: v1consortium.services.OrganizationService.ListUsers:output_type -> v1consortium.services.ListUsersResponse
	19, // 47: v1consortium.services.OrganizationService.DeactivateUser:output_type -> v1consortium.services.DeactivateUserResponse
	21, // 48: v1consortium.services.OrganizationService.CreateSubscription:output_type -> v1consortium.services.CreateSubscriptionResponse
	23, // 49: v1consortium.services.OrganizationService.GetSubscription:output_type -> v1consortium.services.GetSubscriptionResponse
	25, // 50: v1consortium.services.OrganizationService.UpdateSubscription:output_type -> v1consortium.services.UpdateSubscriptionResponse
	27, // 51: v1consortium.services.OrganizationService.ListSubscriptionPlans:output_type -> v1consortium.services.ListSubscriptionPlansResponse
	38, // [38:52] is the sub-list for method output_type
	24, // [24:38] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_services_v1_organization_proto_init() }
func file_services_v1_organization_proto_init() {
	if File_services_v1_organization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_v1_organization_proto_rawDesc), len(file_services_v1_organization_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_organization_proto_goTypes,
		DependencyIndexes: file_services_v1_organization_proto_depIdxs,
		MessageInfos:      file_services_v1_organization_proto_msgTypes,
	}.Build()
	File_services_v1_organization_proto = out.File
	file_services_v1_organization_proto_goTypes = nil
	file_services_v1_organization_proto_depIdxs = nil
}
