// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pbentity/background_check_findings.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackgroundCheckFindings struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Id                               string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`                                                               //
	BackgroundCheckId                string                 `protobuf:"bytes,2,opt,name=BackgroundCheckId,proto3" json:"BackgroundCheckId,omitempty"`                                 //
	FindingType                      string                 `protobuf:"bytes,3,opt,name=FindingType,proto3" json:"FindingType,omitempty"`                                             //
	Severity                         string                 `protobuf:"bytes,4,opt,name=Severity,proto3" json:"Severity,omitempty"`                                                   //
	Description                      string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`                                             //
	DateOfRecord                     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=DateOfRecord,proto3" json:"DateOfRecord,omitempty"`                                           //
	Jurisdiction                     string                 `protobuf:"bytes,7,opt,name=Jurisdiction,proto3" json:"Jurisdiction,omitempty"`                                           //
	CaseNumber                       string                 `protobuf:"bytes,8,opt,name=CaseNumber,proto3" json:"CaseNumber,omitempty"`                                               //
	Disposition                      string                 `protobuf:"bytes,9,opt,name=Disposition,proto3" json:"Disposition,omitempty"`                                             //
	JobRelated                       bool                   `protobuf:"varint,10,opt,name=JobRelated,proto3" json:"JobRelated,omitempty"`                                             //
	Disqualifying                    bool                   `protobuf:"varint,11,opt,name=Disqualifying,proto3" json:"Disqualifying,omitempty"`                                       //
	RequiresIndividualizedAssessment bool                   `protobuf:"varint,12,opt,name=RequiresIndividualizedAssessment,proto3" json:"RequiresIndividualizedAssessment,omitempty"` //
	CreatedAt                        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                                                //
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *BackgroundCheckFindings) Reset() {
	*x = BackgroundCheckFindings{}
	mi := &file_pbentity_background_check_findings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundCheckFindings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundCheckFindings) ProtoMessage() {}

func (x *BackgroundCheckFindings) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_background_check_findings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundCheckFindings.ProtoReflect.Descriptor instead.
func (*BackgroundCheckFindings) Descriptor() ([]byte, []int) {
	return file_pbentity_background_check_findings_proto_rawDescGZIP(), []int{0}
}

func (x *BackgroundCheckFindings) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackgroundCheckFindings) GetBackgroundCheckId() string {
	if x != nil {
		return x.BackgroundCheckId
	}
	return ""
}

func (x *BackgroundCheckFindings) GetFindingType() string {
	if x != nil {
		return x.FindingType
	}
	return ""
}

func (x *BackgroundCheckFindings) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *BackgroundCheckFindings) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BackgroundCheckFindings) GetDateOfRecord() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfRecord
	}
	return nil
}

func (x *BackgroundCheckFindings) GetJurisdiction() string {
	if x != nil {
		return x.Jurisdiction
	}
	return ""
}

func (x *BackgroundCheckFindings) GetCaseNumber() string {
	if x != nil {
		return x.CaseNumber
	}
	return ""
}

func (x *BackgroundCheckFindings) GetDisposition() string {
	if x != nil {
		return x.Disposition
	}
	return ""
}

func (x *BackgroundCheckFindings) GetJobRelated() bool {
	if x != nil {
		return x.JobRelated
	}
	return false
}

func (x *BackgroundCheckFindings) GetDisqualifying() bool {
	if x != nil {
		return x.Disqualifying
	}
	return false
}

func (x *BackgroundCheckFindings) GetRequiresIndividualizedAssessment() bool {
	if x != nil {
		return x.RequiresIndividualizedAssessment
	}
	return false
}

func (x *BackgroundCheckFindings) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pbentity_background_check_findings_proto protoreflect.FileDescriptor

const file_pbentity_background_check_findings_proto_rawDesc = "" +
	"\n" +
	"(pbentity/background_check_findings.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x04\n" +
	"\x17BackgroundCheckFindings\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12,\n" +
	"\x11BackgroundCheckId\x18\x02 \x01(\tR\x11BackgroundCheckId\x12 \n" +
	"\vFindingType\x18\x03 \x01(\tR\vFindingType\x12\x1a\n" +
	"\bSeverity\x18\x04 \x01(\tR\bSeverity\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12>\n" +
	"\fDateOfRecord\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fDateOfRecord\x12\"\n" +
	"\fJurisdiction\x18\a \x01(\tR\fJurisdiction\x12\x1e\n" +
	"\n" +
	"CaseNumber\x18\b \x01(\tR\n" +
	"CaseNumber\x12 \n" +
	"\vDisposition\x18\t \x01(\tR\vDisposition\x12\x1e\n" +
	"\n" +
	"JobRelated\x18\n" +
	" \x01(\bR\n" +
	"JobRelated\x12$\n" +
	"\rDisqualifying\x18\v \x01(\bR\rDisqualifying\x12J\n" +
	" RequiresIndividualizedAssessment\x18\f \x01(\bR RequiresIndividualizedAssessment\x128\n" +
	"\tCreatedAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAtB\x1bZ\x19v1consortium/api/pbentityb\x06proto3"

var (
	file_pbentity_background_check_findings_proto_rawDescOnce sync.Once
	file_pbentity_background_check_findings_proto_rawDescData []byte
)

func file_pbentity_background_check_findings_proto_rawDescGZIP() []byte {
	file_pbentity_background_check_findings_proto_rawDescOnce.Do(func() {
		file_pbentity_background_check_findings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_background_check_findings_proto_rawDesc), len(file_pbentity_background_check_findings_proto_rawDesc)))
	})
	return file_pbentity_background_check_findings_proto_rawDescData
}

var file_pbentity_background_check_findings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_background_check_findings_proto_goTypes = []any{
	(*BackgroundCheckFindings)(nil), // 0: pbentity.BackgroundCheckFindings
	(*timestamppb.Timestamp)(nil),   // 1: google.protobuf.Timestamp
}
var file_pbentity_background_check_findings_proto_depIdxs = []int32{
	1, // 0: pbentity.BackgroundCheckFindings.DateOfRecord:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.BackgroundCheckFindings.CreatedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbentity_background_check_findings_proto_init() }
func file_pbentity_background_check_findings_proto_init() {
	if File_pbentity_background_check_findings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_background_check_findings_proto_rawDesc), len(file_pbentity_background_check_findings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_background_check_findings_proto_goTypes,
		DependencyIndexes: file_pbentity_background_check_findings_proto_depIdxs,
		MessageInfos:      file_pbentity_background_check_findings_proto_msgTypes,
	}.Build()
	File_pbentity_background_check_findings_proto = out.File
	file_pbentity_background_check_findings_proto_goTypes = nil
	file_pbentity_background_check_findings_proto_depIdxs = nil
}
