// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pbentity/saved_reports.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SavedReports struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`                                //
	OrganizationId    string                 `protobuf:"bytes,2,opt,name=OrganizationId,proto3" json:"OrganizationId,omitempty"`        //
	CreatedBy         string                 `protobuf:"bytes,3,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`                  //
	Name              string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`                            //
	Description       string                 `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`              //
	ReportType        string                 `protobuf:"bytes,6,opt,name=ReportType,proto3" json:"ReportType,omitempty"`                //
	Parameters        string                 `protobuf:"bytes,7,opt,name=Parameters,proto3" json:"Parameters,omitempty"`                //
	Filters           string                 `protobuf:"bytes,8,opt,name=Filters,proto3" json:"Filters,omitempty"`                      //
	GeneratedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=GeneratedAt,proto3" json:"GeneratedAt,omitempty"`              //
	FilePath          string                 `protobuf:"bytes,10,opt,name=FilePath,proto3" json:"FilePath,omitempty"`                   //
	FileFormat        string                 `protobuf:"bytes,11,opt,name=FileFormat,proto3" json:"FileFormat,omitempty"`               //
	IsScheduled       bool                   `protobuf:"varint,12,opt,name=IsScheduled,proto3" json:"IsScheduled,omitempty"`            //
	ScheduleFrequency string                 `protobuf:"bytes,13,opt,name=ScheduleFrequency,proto3" json:"ScheduleFrequency,omitempty"` //
	NextRunDate       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=NextRunDate,proto3" json:"NextRunDate,omitempty"`             //
	IsPublic          bool                   `protobuf:"varint,15,opt,name=IsPublic,proto3" json:"IsPublic,omitempty"`                  //
	SharedWith        string                 `protobuf:"bytes,16,opt,name=SharedWith,proto3" json:"SharedWith,omitempty"`               //
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`                 //
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`                 //
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SavedReports) Reset() {
	*x = SavedReports{}
	mi := &file_pbentity_saved_reports_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedReports) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedReports) ProtoMessage() {}

func (x *SavedReports) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_saved_reports_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedReports.ProtoReflect.Descriptor instead.
func (*SavedReports) Descriptor() ([]byte, []int) {
	return file_pbentity_saved_reports_proto_rawDescGZIP(), []int{0}
}

func (x *SavedReports) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SavedReports) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *SavedReports) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *SavedReports) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SavedReports) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SavedReports) GetReportType() string {
	if x != nil {
		return x.ReportType
	}
	return ""
}

func (x *SavedReports) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

func (x *SavedReports) GetFilters() string {
	if x != nil {
		return x.Filters
	}
	return ""
}

func (x *SavedReports) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *SavedReports) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SavedReports) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

func (x *SavedReports) GetIsScheduled() bool {
	if x != nil {
		return x.IsScheduled
	}
	return false
}

func (x *SavedReports) GetScheduleFrequency() string {
	if x != nil {
		return x.ScheduleFrequency
	}
	return ""
}

func (x *SavedReports) GetNextRunDate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunDate
	}
	return nil
}

func (x *SavedReports) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *SavedReports) GetSharedWith() string {
	if x != nil {
		return x.SharedWith
	}
	return ""
}

func (x *SavedReports) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SavedReports) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_pbentity_saved_reports_proto protoreflect.FileDescriptor

const file_pbentity_saved_reports_proto_rawDesc = "" +
	"\n" +
	"\x1cpbentity/saved_reports.proto\x12\bpbentity\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x05\n" +
	"\fSavedReports\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12&\n" +
	"\x0eOrganizationId\x18\x02 \x01(\tR\x0eOrganizationId\x12\x1c\n" +
	"\tCreatedBy\x18\x03 \x01(\tR\tCreatedBy\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x05 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"ReportType\x18\x06 \x01(\tR\n" +
	"ReportType\x12\x1e\n" +
	"\n" +
	"Parameters\x18\a \x01(\tR\n" +
	"Parameters\x12\x18\n" +
	"\aFilters\x18\b \x01(\tR\aFilters\x12<\n" +
	"\vGeneratedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vGeneratedAt\x12\x1a\n" +
	"\bFilePath\x18\n" +
	" \x01(\tR\bFilePath\x12\x1e\n" +
	"\n" +
	"FileFormat\x18\v \x01(\tR\n" +
	"FileFormat\x12 \n" +
	"\vIsScheduled\x18\f \x01(\bR\vIsScheduled\x12,\n" +
	"\x11ScheduleFrequency\x18\r \x01(\tR\x11ScheduleFrequency\x12<\n" +
	"\vNextRunDate\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vNextRunDate\x12\x1a\n" +
	"\bIsPublic\x18\x0f \x01(\bR\bIsPublic\x12\x1e\n" +
	"\n" +
	"SharedWith\x18\x10 \x01(\tR\n" +
	"SharedWith\x128\n" +
	"\tCreatedAt\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tUpdatedAt\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAtB\x1bZ\x19v1consortium/api/pbentityb\x06proto3"

var (
	file_pbentity_saved_reports_proto_rawDescOnce sync.Once
	file_pbentity_saved_reports_proto_rawDescData []byte
)

func file_pbentity_saved_reports_proto_rawDescGZIP() []byte {
	file_pbentity_saved_reports_proto_rawDescOnce.Do(func() {
		file_pbentity_saved_reports_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_saved_reports_proto_rawDesc), len(file_pbentity_saved_reports_proto_rawDesc)))
	})
	return file_pbentity_saved_reports_proto_rawDescData
}

var file_pbentity_saved_reports_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_saved_reports_proto_goTypes = []any{
	(*SavedReports)(nil),          // 0: pbentity.SavedReports
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_saved_reports_proto_depIdxs = []int32{
	1, // 0: pbentity.SavedReports.GeneratedAt:type_name -> google.protobuf.Timestamp
	1, // 1: pbentity.SavedReports.NextRunDate:type_name -> google.protobuf.Timestamp
	1, // 2: pbentity.SavedReports.CreatedAt:type_name -> google.protobuf.Timestamp
	1, // 3: pbentity.SavedReports.UpdatedAt:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pbentity_saved_reports_proto_init() }
func file_pbentity_saved_reports_proto_init() {
	if File_pbentity_saved_reports_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_saved_reports_proto_rawDesc), len(file_pbentity_saved_reports_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_saved_reports_proto_goTypes,
		DependencyIndexes: file_pbentity_saved_reports_proto_depIdxs,
		MessageInfos:      file_pbentity_saved_reports_proto_msgTypes,
	}.Build()
	File_pbentity_saved_reports_proto = out.File
	file_pbentity_saved_reports_proto_goTypes = nil
	file_pbentity_saved_reports_proto_depIdxs = nil
}
