// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"v1consortium/internal/dao/internal"
)

// complianceStatusDao is the data access object for the table compliance_status.
// You can define custom methods on it to extend its functionality as needed.
type complianceStatusDao struct {
	*internal.ComplianceStatusDao
}

var (
	// ComplianceStatus is a globally accessible object for table compliance_status operations.
	ComplianceStatus = complianceStatusDao{internal.NewComplianceStatusDao()}
)

// Add your custom methods and functionality below.
