// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"v1consortium/internal/dao/internal"
)

// dotPhysicalsDao is the data access object for the table dot_physicals.
// You can define custom methods on it to extend its functionality as needed.
type dotPhysicalsDao struct {
	*internal.DotPhysicalsDao
}

var (
	// DotPhysicals is a globally accessible object for table dot_physicals operations.
	DotPhysicals = dotPhysicalsDao{internal.NewDotPhysicalsDao()}
)

// Add your custom methods and functionality below.
