// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"v1consortium/internal/dao/internal"
)

// randomTestingPoolsDao is the data access object for the table random_testing_pools.
// You can define custom methods on it to extend its functionality as needed.
type randomTestingPoolsDao struct {
	*internal.RandomTestingPoolsDao
}

var (
	// RandomTestingPools is a globally accessible object for table random_testing_pools operations.
	RandomTestingPools = randomTestingPoolsDao{internal.NewRandomTestingPoolsDao()}
)

// Add your custom methods and functionality below.
