// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"v1consortium/internal/dao/internal"
)

// testingProgramsDao is the data access object for the table testing_programs.
// You can define custom methods on it to extend its functionality as needed.
type testingProgramsDao struct {
	*internal.TestingProgramsDao
}

var (
	// TestingPrograms is a globally accessible object for table testing_programs operations.
	TestingPrograms = testingProgramsDao{internal.NewTestingProgramsDao()}
)

// Add your custom methods and functionality below.
